### ISSUE TITLE
Always got "blob=XXXX" for preview?

### ISSUE THREAD

**Issue by LtdFi** [prologic/pastebin#8]
Using https://paste.mills.io/

![image](https://user-images.githubusercontent.com/81313384/113025989-27592e80-91bb-11eb-8fcb-4eb70421c937.png)

Then I got:

![image](https://user-images.githubusercontent.com/81313384/113026020-2f18d300-91bb-11eb-985c-86a413518c62.png)

Why can't I get a clean text to repro?

**Comment by prologic** [comment]
Bug I think 🤣

Can you fix it?

**Comment by prologic** [comment]
Fixed via 93cce3b
