### ISSUE TITLE
Random urls are reused

### ISSUE THREAD

**Issue by taigrr** [prologic/pastebin#9]
Tested on both paste.taigrr.com and paste.mills.io, a random url is generated at program start, but every blob ever sent gets the same url. 

For example, no matter what you put in the text box, you get these urls:

 https://paste.mills.io/p/5oghcdgpk68B86gJkG2aGM

https://paste.taigrr.com/p/SjUczAPPhrP4ySNiEifYUX

I'll take a look into fixing this later if nobody else gets to it.

Sorry for formatting, I'm on mobile. I'll probably go back later and fix it.

**Comment by prologic** [comment]
Ooops

**Comment by taigrr** [comment]
Wait, why was this closed?

**Comment by prologic** [comment]
I fixed the bug 🤣

**Comment by taigrr** [comment]
Totally missed the referenced commit. See it now, works great thanks!

**Comment by prologic** [comment]
No problems!
